### PR TITLE
ignore some stuff and prepublish build

### PR DESCRIPTION
**Pull request by sergey-lapin**
Thanks for this package, great work!
I have some problems with using it with webpack so I made this PR to build your code on prepublish. 
What do think?

### CODE REVIEW

**Comment by gre** [comment]
Thanks for your fixes,
I don't know how webpack works but does your fix also help webpack to locate the entrypoint file?

**Comment by sergey-lapin** [comment]
It just lowers configuration barrier as you ship compiled es5 code, so user just can use it without building step, I  just had some issues with configuration webpack for prebuilding this.

**Comment by sergey-lapin** [comment]
@gre could you merge this?

**Comment by gre** [comment]
yeah sure

**Comment by sergey-lapin** [comment]
Could you publish it to npm so I could test this? Ahh I actualy think that I forget to change main package.json..

**Comment by sergey-lapin** [comment]
@gre https://github.com/gre/bezier-easing-editor/pull/2

**Comment by gre** [comment]
Yeah I've seen it and fixed it. Thanks.

**Comment by sergey-lapin** [comment]
Thanks you)

**Pull request merged**
